/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * User API
 * API for managing users
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod'


/**
 * @summary Get list of orders
 */
export const getOrdersResponseItem = zod.object({
  "id": zod.string(),
  "userId": zod.string(),
  "items": zod.array(zod.object({
  "productId": zod.string().optional(),
  "quantity": zod.number().optional()
})),
  "total": zod.number(),
  "createdAt": zod.string().datetime().optional(),
  "updatedAt": zod.string().datetime().optional()
})
export const getOrdersResponse = zod.array(getOrdersResponseItem)

/**
 * @summary Create a new order
 */
export const postOrdersBody = zod.object({
  "id": zod.string(),
  "userId": zod.string(),
  "items": zod.array(zod.object({
  "productId": zod.string().optional(),
  "quantity": zod.number().optional()
})),
  "total": zod.number(),
  "createdAt": zod.string().datetime().optional(),
  "updatedAt": zod.string().datetime().optional()
})

/**
 * @summary Get an order by ID
 */
export const getOrdersIdParams = zod.object({
  "id": zod.string()
})

export const getOrdersIdResponse = zod.object({
  "id": zod.string(),
  "userId": zod.string(),
  "items": zod.array(zod.object({
  "productId": zod.string().optional(),
  "quantity": zod.number().optional()
})),
  "total": zod.number(),
  "createdAt": zod.string().datetime().optional(),
  "updatedAt": zod.string().datetime().optional()
})

/**
 * @summary Update an order by ID
 */
export const putOrdersIdParams = zod.object({
  "id": zod.string()
})

export const putOrdersIdBody = zod.object({
  "id": zod.string(),
  "userId": zod.string(),
  "items": zod.array(zod.object({
  "productId": zod.string().optional(),
  "quantity": zod.number().optional()
})),
  "total": zod.number(),
  "createdAt": zod.string().datetime().optional(),
  "updatedAt": zod.string().datetime().optional()
})

export const putOrdersIdResponse = zod.object({
  "id": zod.string(),
  "userId": zod.string(),
  "items": zod.array(zod.object({
  "productId": zod.string().optional(),
  "quantity": zod.number().optional()
})),
  "total": zod.number(),
  "createdAt": zod.string().datetime().optional(),
  "updatedAt": zod.string().datetime().optional()
})

/**
 * @summary Delete an order by ID
 */
export const deleteOrdersIdParams = zod.object({
  "id": zod.string()
})

