/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * User API
 * API for managing users
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod'


/**
 * @summary Get list of users
 */
export const getUsersResponseItem = zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "email": zod.string(),
  "createdAt": zod.string().datetime().optional(),
  "updatedAt": zod.string().datetime().optional()
})
export const getUsersResponse = zod.array(getUsersResponseItem)

/**
 * @summary Create a new user
 */
export const postUsersBody = zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "email": zod.string(),
  "createdAt": zod.string().datetime().optional(),
  "updatedAt": zod.string().datetime().optional()
})

/**
 * @summary Get a user by ID
 */
export const getUsersIdParams = zod.object({
  "id": zod.string()
})

export const getUsersIdResponse = zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "email": zod.string(),
  "createdAt": zod.string().datetime().optional(),
  "updatedAt": zod.string().datetime().optional()
})

/**
 * @summary Update a user by ID
 */
export const putUsersIdParams = zod.object({
  "id": zod.string()
})

export const putUsersIdBody = zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "email": zod.string(),
  "createdAt": zod.string().datetime().optional(),
  "updatedAt": zod.string().datetime().optional()
})

export const putUsersIdResponse = zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "email": zod.string(),
  "createdAt": zod.string().datetime().optional(),
  "updatedAt": zod.string().datetime().optional()
})

/**
 * @summary Delete a user by ID
 */
export const deleteUsersIdParams = zod.object({
  "id": zod.string()
})

