/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * User API
 * API for managing users
 * OpenAPI spec version: 1.0.0
 */
import type { OrderItemsItem } from './orderItemsItem';

export interface Order {
  createdAt?: string;
  id: string;
  items: OrderItemsItem[];
  total: number;
  updatedAt?: string;
  userId: string;
}
