/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * User API
 * API for managing users
 * OpenAPI spec version: 1.0.0
 */

export interface User {
  createdAt?: string;
  email: string;
  id: string;
  name: string;
  updatedAt?: string;
}
